### ISSUE TITLE
Program crashes on preview or render

### ISSUE THREAD

**Issue by thegreatestminer** [arduano/Zenith-MIDI#3]
Title is pretty self-explanatory.

This is what the console output gave, hopefully I was able to type it down properly.

```
Unhanded Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
    at OpenTK.Graphics.OpenGL.GL.GenFramebuffer()
    at Black_Midi_Render.GLUtils.GenFrameBufferTexture(Int32 width, Int32 height, Int32& fbuffer, Int32& rtexture)
    at Black_Midi_Render.RenderWindows..ctor(CurrentRendererPointer renderer, MidiFile midi, RenderSettings settings)
    at Black_Midi_Render.MainWindows.()c__DisplayClass13_0.(RunRenderWindow)b__0()

    at System.Threading.Tasks.Task.InnerInvoke()
    at System.Threading.Tasks.Task.Execute()
    at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
    at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
    at System.Threading.ThreadPoolWorkQueue.Dispatch()
    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

I'm assuming that this program need a higher version of OpenGL, considering my version is 2.0. (integrated graphics are a pain, lol)

**Comment by arduano** [comment]
Yeah this is a common issue that has been discussed quite a lot in the bug reports channel on the discord server. The answer is simple: your version of OpenGL doesn't support frame buffers and therefore can't run Zenith. `at OpenTK.Graphics.OpenGL.GL.GenFramebuffer()` <- if something crashes on this line then it's OpenGL's fault.

**Comment by thegreatestminer** [comment]
Hm, just as a note, I'd recommend saying that Zenith requires OGL 3.0 on the front page or something.

Hell, maybe add a startup check to find what version the computer has, and prevent program use if it's too low.

Thanks for the info!

**Comment by arduano** [comment]
Technically Zenith does support some lower versions of opengl, I think keppy managed to make it work on a system with 2.1

The percentage of users that have cards which don't support zenith's opengl is really quite low, many people with complete potatoes can still run it. But I'll see if any changes are necessary...
